site_name: Gentoo on the Raspberry Pi
pages:
- Home: index.md
- Kernel:
    - Kernel Building: Kernel\2.5 Custom Kernel.md
    - 64Bit Kernel: Kernel\64bit Kernel.md

theme: slate
#theme: alabaster
#theme: readthedocs
#theme: mkdocs

markdown_extensions:
    - smarty

extra_css:
    - css/highlight-fix.css
    - css/highlight-custom.css
